### ISSUE TITLE
Вторым аргументом ты задаешь индекс, по этому называй эту переменную правильно. Либо i либо index

### ISSUE THREAD

**Issue by scandy5** [YevhenTkachuk/Uber-eats-React#12]
https://github.com/YevhenTkachuk/Uber-eats-React/blob/bd7b99ea3ed15dcc15d9e00d0cf3f2d36c766eb4/src/Restaurant-menu/Restaurant-menu.jsx#L11

**Comment by YevhenTkachuk** [comment]
Done
