### ISSUE TITLE
если ты называешь папки с компонентами с большой буквы, то уже делай это со всеми папками компонентов

### ISSUE THREAD

**Issue by scandy5** [YevhenTkachuk/Uber-eats-React#3]
![image](https://user-images.githubusercontent.com/41551315/60589071-3e2ddf80-9da1-11e9-9810-b66f21cc5493.png)
А так же, используй camelCase для названий папок и файлов компонентов

**Comment by YevhenTkachuk** [comment]
У меня в веб шторме все с большой а в гите некоторые с маленькой ) не знаю что делать в таком случае

**Comment by scandy5** [comment]
Я не удивлен, что всё папки стали с нормальными именами)
