### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by scandy5** [YevhenTkachuk/Uber-eats-React#5]
https://github.com/YevhenTkachuk/Uber-eats-React/blob/bd7b99ea3ed15dcc15d9e00d0cf3f2d36c766eb4/src/restaurants-choose/Restaurants-choose.jsx#L9
Это главный оберточный тег компонента, тоесть это родительский тег блока и он должен называться так же как и компонент, а все теги внутри него - это элементы блока. Тоесть, название класса этого тега будет **restaurants-choose**
А вот это: https://github.com/YevhenTkachuk/Uber-eats-React/blob/bd7b99ea3ed15dcc15d9e00d0cf3f2d36c766eb4/src/restaurants-choose/Restaurants-choose.jsx#L13 элемент твоего главного блока и он не должен быть назван таким классом. Корректное имя класса будет **restaurants-choose__link** ну или что-то аналогичное.

**Comment by YevhenTkachuk** [comment]
Done
